### ISSUE TITLE
I can only invite by user ID and not by username

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-bulk-invite#8]
There is a sample file here https://github.com/mattermost/mattermost-plugin-bulk-invite/blob/master/.readme/template.jsonc it suggests that I can import users by username. 

For me this does not work. The record that is a username is getting ignored. My file looks like this:
```
{
    "users": [
        {
            "user_id": "uc8xmpnyabb9fdsi8118h57b7h",
            "user_id": "h1ifmik7airimbwb6b5iqh4bsy",
            "user_id": "ub993654zbgaxfi6u8i4h3mqjw",
            "user_id": "kg7am5zpwirrxf13xd1qu51e3c",                        
            "username": "aaron.medina"
        }
    ]
}
```  
The user does exist by that name on the server (and is a member of the team)
![image](https://github.com/mattermost/mattermost-plugin-bulk-invite/assets/35588783/318bf5c4-3654-4c8c-a472-3f023a14b41b)

Please advise if I have misnderstood something here.

**Comment by fmartingr** [comment]
The file you need to create should look like this:

```
{
    "users": [
        {
            "user_id": "uc8xmpnyabb9fdsi8118h57b7h"
        },{
            "user_id": "h1ifmik7airimbwb6b5iqh4bsy"
        },{
            "user_id": "ub993654zbgaxfi6u8i4h3mqjw"
        },{
            "user_id": "kg7am5zpwirrxf13xd1qu51e3c"
        },{               
            "username": "aaron.medina"
        }
    ]
}
```

I will clarify that in the template document.
